//
// Generated file, do not edit! Created by opp_msgc 4.3 from messages/IDSVotingResponsePkt.msg.
//

#ifndef _IDSVOTINGRESPONSEPKT_M_H_
#define _IDSVOTINGRESPONSEPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "NetwPkt_m.h"
// }}



/**
 * Class generated from <tt>messages/IDSVotingResponsePkt.msg</tt> by opp_msgc.
 * <pre>
 * packet IDSVotingResponsePkt
 * {
 *     LAddress::L3Type destAddr;   
 *     LAddress::L3Type srcAddr;    
 * 	int nodeID;
 * 	bool isAttacker;
 * }
 * </pre>
 */
class IDSVotingResponsePkt : public ::cPacket
{
  protected:
    LAddress::L3Type destAddr_var;
    LAddress::L3Type srcAddr_var;
    int nodeID_var;
    bool isAttacker_var;

  private:
    void copy(const IDSVotingResponsePkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IDSVotingResponsePkt&);

  public:
    IDSVotingResponsePkt(const char *name=NULL, int kind=0);
    IDSVotingResponsePkt(const IDSVotingResponsePkt& other);
    virtual ~IDSVotingResponsePkt();
    IDSVotingResponsePkt& operator=(const IDSVotingResponsePkt& other);
    virtual IDSVotingResponsePkt *dup() const {return new IDSVotingResponsePkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual LAddress::L3Type& getDestAddr();
    virtual const LAddress::L3Type& getDestAddr() const {return const_cast<IDSVotingResponsePkt*>(this)->getDestAddr();}
    virtual void setDestAddr(const LAddress::L3Type& destAddr);
    virtual LAddress::L3Type& getSrcAddr();
    virtual const LAddress::L3Type& getSrcAddr() const {return const_cast<IDSVotingResponsePkt*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const LAddress::L3Type& srcAddr);
    virtual int getNodeID() const;
    virtual void setNodeID(int nodeID);
    virtual bool getIsAttacker() const;
    virtual void setIsAttacker(bool isAttacker);
};

inline void doPacking(cCommBuffer *b, IDSVotingResponsePkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IDSVotingResponsePkt& obj) {obj.parsimUnpack(b);}


#endif // _IDSVOTINGRESPONSEPKT_M_H_
